# Generated by Django 5.1.4 on 2026-02-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='altura',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ancho',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Niño', 'Niño')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cod',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='forma',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='largo',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='material',
            field=models.CharField(blank=True, choices=[('Fibra de carbono', 'Fibra de carbono'), ('Acetato', 'Acetato'), ('Carey', 'Carey'), ('TR90', 'TR90'), ('Aluminium', 'Aluminium'), ('Engomado', 'Engomado'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='puente',
            field=models.CharField(max_length=5),
        ),
    ]
