# Generated by Django 5.1.4 on 2026-02-19 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketventa',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
