# Generated by Django 5.1.4 on 2025-12-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketventa',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticketventa',
            name='fecha_entrega',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticketventa',
            name='hora_entrega',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
