# Generated by Django 6.0.2 on 2026-04-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ticketventa_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='condicion',
            field=models.CharField(blank=True, choices=[('Miopia-e-Hipermetropia', 'Miopia-e-Hipermetropia'), ('Astigmatismo', 'Astigmatismo'), ('Presbicia', 'Presbicia')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nuevo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='uso',
            field=models.CharField(blank=True, choices=[('Diario', 'Diario'), ('Mensual', 'Mensual'), ('Anual', 'Anual'), ('Cosmetico', 'Cosmetico')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medidavista',
            name='AV_cerca_OD',
            field=models.CharField(blank=True, default=0, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='medidavista',
            name='AV_cerca_OI',
            field=models.CharField(blank=True, default=0, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='medidavista',
            name='AV_lejos_OD',
            field=models.CharField(blank=True, default=0, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='medidavista',
            name='AV_lejos_OI',
            field=models.CharField(blank=True, default=0, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='altura',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ancho',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Nino', 'Nino')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='forma',
            field=models.CharField(blank=True, choices=[('Agatado', 'Agatado'), ('Almendra', 'Almendra'), ('Aviador', 'Aviador'), ('Cuadrado', 'Cuadrado'), ('Redondo', 'Redondo'), ('Exagonal', 'Exagonal'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='largo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, choices=[('Ray-Ban', 'Ray-Ban'), ('OaKley', 'OaKley'), ('Nike', 'Nike'), ('Guess', 'Guess'), ('Tommy-Hilfiger', 'Tommy-Hilfiger'), ('Arnette', 'Arnette'), ('Nano', 'Nano'), ('Otros', 'Otros'), ('Acuvue', 'Acuvue'), ('Air-Optix', 'Air-Optix'), ('Dailies-Aqua', 'Dailies-Aqua'), ('Freshlook', 'Freshlook'), ('Licryl', 'Licryl'), ('Soflens', 'Soflens'), ('Purevision', 'Purevision'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='puente',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(blank=True, choices=[('Grande', 'Grande'), ('Mediana', 'Mediana'), ('Chica', 'Chica')], max_length=50, null=True),
        ),
    ]
