# Generated by Django 5.1.4 on 2025-12-21 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ticketventa_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='KardexMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=4, max_digits=12)),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_promedio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='core.producto')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ticketventa')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
