# Generated by Django 6.0.2 on 2026-04-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_condicion_producto_nuevo_producto_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talla_luna',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
