# Generated by Django 5.1.4 on 2025-12-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cajadia_movimientocaja_pagoticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='categoria',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('COBRANZA', 'Cobranza'), ('COMPRA', 'Compra'), ('GASTO', 'Gasto'), ('AJUSTE', 'Ajuste'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
    ]
