# Generated by Django 6.0.2 on 2026-05-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_talla_luna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Monturas oftálmicas', 'Monturas oftálmicas'), ('Monturas Solares', 'Monturas Solares'), ('Lentes de Contacto', 'Lentes de Contacto'), ('Monturas de Marca', 'Monturas de Marca'), ('Líquidos', 'Líquidos'), ('Accesorios', 'Accesorios')], max_length=50, null=True),
        ),
    ]
