# Generated by Django 6.0.2 on 2026-06-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('LAB_PEDIDO', 'Pedido al Laboratorio'), ('LAB_EN_PROCESO', 'Lunas en fabricación'), ('BISELADO', 'Lunas en Biselado'), ('UV', 'En control de calidad'), ('LISTO', 'Sus lentes ya están listos'), ('ENTREGADO', 'Entregado')], default='LAB_PEDIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='forma',
            field=models.CharField(blank=True, choices=[('Agatado', 'Agatado'), ('Almendra', 'Almendra'), ('Aviador', 'Aviador'), ('Cuadrado', 'Cuadrado'), ('Redondo', 'Redondo'), ('Exagonal', 'Exagonal'), ('Curvo', 'Curvo'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, choices=[('Ray-Ban', 'Ray-Ban'), ('OaKley', 'OaKley'), ('Nike', 'Nike'), ('Guess', 'Guess'), ('Tommy-Hilfiger', 'Tommy-Hilfiger'), ('Arnette', 'Arnette'), ('Nano', 'Nano'), ('AX', 'Armani Exchange'), ('Emporio', 'Emporio Armani'), ('Skechers', 'Skechers'), ('Harley', 'Harley Davidson'), ('Police', 'Police'), ('Adidas', 'Adidas'), ('Fila', 'Fila'), ('Polo', 'Polo'), ('Timberland', 'Timberland'), ('Ralph', 'Ralph'), ('Carolina', 'Carolina Herrera'), ('Tous', 'Tous'), ('Vogue', 'Vogue'), ('Otros', 'Otros'), ('Acuvue', 'Acuvue'), ('Air-Optix', 'Air-Optix'), ('Dailies-Aqua', 'Dailies-Aqua'), ('Freshlook', 'Freshlook'), ('Licryl', 'Licryl'), ('Soflens', 'Soflens'), ('Purevision', 'Purevision'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='material',
            field=models.CharField(blank=True, choices=[('Fibra de carbono', 'Fibra de carbono'), ('Acetato', 'Acetato'), ('Carey', 'Carey'), ('TR90', 'TR90'), ('Aluminium', 'Aluminium'), ('Metal', 'Metal'), ('Engomado', 'Engomado'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
    ]
