# Generated by Django 6.0.2 on 2026-06-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ordentrabajo_estado_alter_producto_forma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='forma',
            field=models.CharField(blank=True, choices=[('Agatado', 'Agatado'), ('Almendra', 'Almendra'), ('Aviador', 'Aviador'), ('Cuadrado', 'Cuadrado'), ('Rectangular', 'Rectangular'), ('Redondo', 'Redondo'), ('Ovalado', 'Ovalado'), ('Exagonal', 'Exagonal'), ('Curvo', 'Curvo'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='material',
            field=models.CharField(blank=True, choices=[('Fibra de carbono', 'Fibra de carbono'), ('Acetato', 'Acetato'), ('Carey', 'Carey'), ('TR90', 'TR90'), ('Aluminium', 'Aluminium'), ('Titanio', 'Titanio'), ('Metal', 'Metal'), ('Engomado', 'Engomado'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
    ]
