# Generated by Django 6.0.2 on 2026-06-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_producto_forma_alter_producto_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='control_menor_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='encuesta_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='renovacion_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
