# Generated by Django 6.0.2 on 2026-06-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ordentrabajo_control_menor_enviado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
