# Generated by Django 6.0.2 on 2026-06-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_producto_precio_promo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_promo',
            new_name='precio_anterior',
        ),
    ]
