# Generated by Django 6.0.2 on 2026-06-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_precio_promo_producto_precio_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_ultima_renovacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_ultimo_control_menor',
            field=models.DateField(blank=True, null=True),
        ),
    ]
