# Generated by Django 6.0.2 on 2026-07-20 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ordentrabajo_fecha_ultima_renovacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='excluir_reactivacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_ultima_reactivacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReactivacionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(max_length=10)),
                ('monto_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('respondio', models.BooleanField(default=False)),
                ('genero_venta', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivaciones', to='core.cliente')),
            ],
        ),
    ]
