# Generated by Django 6.0.2 on 2026-08-16 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGerencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='contabilidad.categoriagerencial')),
            ],
            options={
                'verbose_name': 'Categoría gerencial',
                'verbose_name_plural': 'Categorías gerenciales',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('centro_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcentros', to='contabilidad.centrocosto')),
            ],
            options={
                'verbose_name': 'Centro de costo',
                'verbose_name_plural': 'Centros de costo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_pcge', models.CharField(blank=True, help_text='Código PCGE de referencia.', max_length=20)),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('COSTO', 'Costo'), ('GASTO', 'Gasto')], max_length=20)),
                ('naturaleza', models.CharField(choices=[('DEUDORA', 'Deudora'), ('ACREEDORA', 'Acreedora')], max_length=15)),
                ('estado_financiero', models.CharField(choices=[('ESF', 'Estado de Situación Financiera'), ('ER', 'Estado de Resultados'), ('ECP', 'Estado de Cambios en el Patrimonio'), ('EFE', 'Estado de Flujos de Efectivo'), ('NINGUNO', 'No aplica')], default='NINGUNO', max_length=10)),
                ('nivel', models.PositiveSmallIntegerField(default=1)),
                ('acepta_movimientos', models.BooleanField(default=True, help_text='Si está desactivado, la cuenta solo sirve para agrupar otras cuentas.')),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcuentas', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contables',
                'ordering': ['codigo'],
            },
        ),
    ]
