# Generated by Django 6.0.2 on 2026-08-16 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=30, unique=True)),
                ('nombre', models.CharField(db_index=True, help_text='Nombre que verá y buscará el usuario.', max_length=200)),
                ('es_grupo', models.BooleanField(default=False, help_text='Si está activo, el concepto sirve para agrupar otros conceptos y no debería usarse como operación final.')),
                ('tipo_operacion', models.CharField(choices=[('GASTO', 'Gasto'), ('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('INGRESO', 'Ingreso'), ('PAGO', 'Pago'), ('COBRO', 'Cobro'), ('ACTIVO', 'Compra de activo'), ('FINANCIAMIENTO', 'Financiamiento'), ('OTRO', 'Otro')], default='GASTO', max_length=20)),
                ('palabras_clave', models.CharField(blank=True, help_text='Palabras relacionadas separadas por comas. Ej.: papel, hojas, bond, resma, oficina.', max_length=500)),
                ('sinonimos', models.CharField(blank=True, help_text='Sinónimos o formas alternativas usadas por el personal.', max_length=500)),
                ('requiere_proveedor', models.BooleanField(default=False)),
                ('requiere_cliente', models.BooleanField(default=False)),
                ('requiere_comprobante', models.BooleanField(default=False)),
                ('requiere_centro_costo', models.BooleanField(default=False)),
                ('permite_cambiar_cuenta', models.BooleanField(default=False, help_text='Permite que un usuario autorizado cambie la cuenta sugerida antes de contabilizar.')),
                ('es_fijo', models.BooleanField(default=False, help_text='Indica si normalmente se considera costo/gasto fijo.')),
                ('es_variable', models.BooleanField(default=True, help_text='Indica si normalmente se considera costo/gasto variable.')),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria_gerencial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_operacion', to='contabilidad.categoriagerencial')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_operacion', to='contabilidad.centrocosto')),
                ('concepto_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subconceptos', to='contabilidad.conceptooperacion')),
                ('cuenta_contable', models.ForeignKey(blank=True, help_text='Cuenta contable principal sugerida para este concepto.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_operacion', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Concepto de operación',
                'verbose_name_plural': 'Conceptos de operación',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
