# Generated by Django 6.0.2 on 2026-08-17 03:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_conceptooperacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
            ],
            options={
                'verbose_name': 'Periodo contable',
                'verbose_name_plural': 'Periodos contables',
                'ordering': ['-anio', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('anio', 'mes'), name='unique_periodo_contable'), models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='mes_contable_valido')],
            },
        ),
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveBigIntegerField(db_index=True)),
                ('fecha', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático'), ('AJUSTE', 'Ajuste'), ('APERTURA', 'Apertura'), ('CIERRE', 'Cierre')], default='MANUAL', max_length=15)),
                ('glosa', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONTABILIZADO', 'Contabilizado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('origen', models.CharField(blank=True, help_text='Ej.: VENTA, COMPRA, PAGO, PLANILLA, DEPRECIACION, MANUAL.', max_length=50)),
                ('origen_id', models.PositiveBigIntegerField(blank=True, help_text='ID del objeto que originó automáticamente el asiento.', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='contabilidad.periodocontable')),
            ],
            options={
                'verbose_name': 'Asiento contable',
                'verbose_name_plural': 'Asientos contables',
                'ordering': ['fecha', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.PositiveSmallIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('referencia', models.CharField(blank=True, help_text='Factura, boleta, ticket, orden de trabajo, etc.', max_length=100)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.asientocontable')),
                ('categoria_gerencial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.categoriagerencial')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.centrocosto')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Detalle de asiento',
                'verbose_name_plural': 'Detalles de asiento',
                'ordering': ['asiento', 'secuencia'],
                'constraints': [models.UniqueConstraint(fields=('asiento', 'secuencia'), name='unique_secuencia_detalle_asiento'), models.CheckConstraint(condition=models.Q(('debe__gte', 0)), name='detalle_debe_no_negativo'), models.CheckConstraint(condition=models.Q(('haber__gte', 0)), name='detalle_haber_no_negativo'), models.CheckConstraint(condition=models.Q(models.Q(('debe__gt', 0), ('haber', 0)), models.Q(('debe', 0), ('haber__gt', 0)), _connector='OR'), name='detalle_solo_debe_o_haber')],
            },
        ),
        migrations.AddConstraint(
            model_name='asientocontable',
            constraint=models.UniqueConstraint(fields=('periodo', 'numero'), name='unique_numero_asiento_por_periodo'),
        ),
    ]
