# Generated by Django 6.0.2 on 2026-08-20 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_periodocontable_asientocontable_detalleasiento_and_more'),
        ('core', '0012_cliente_excluir_reactivacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaCostoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADA', 'Validada'), ('CONTABILIZADA', 'Contabilizada')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
                ('contabilizado_en', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='propuesta_costo_contable', to='core.ticketventa')),
            ],
            options={
                'verbose_name': 'Propuesta de costo de venta',
                'verbose_name_plural': 'Propuestas de costo de venta',
                'ordering': ['-ticket__fecha_emision', '-ticket__numero'],
            },
        ),
        migrations.CreateModel(
            name='DetallePropuestaCostoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('origen_costo', models.CharField(choices=[('KARDEX', 'Kardex de la venta'), ('PROMEDIO', 'Costo promedio ponderado'), ('MANUAL', 'Ingresado manualmente'), ('SIN_COSTO', 'Sin costo registrado')], default='SIN_COSTO', max_length=15)),
                ('validado', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=300)),
                ('detalle_ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='costo_contable', to='core.detalleticketventa')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.propuestacostoventa')),
            ],
            options={
                'verbose_name': 'Detalle de costo de venta',
                'verbose_name_plural': 'Detalles de costo de venta',
                'ordering': ['id'],
            },
        ),
    ]
