# Generated by Django 6.0.2 on 2026-08-20 05:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_propuestacostoventa_detallepropuestacostoventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraDirectaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(blank=True, help_text='Nombre del proveedor. Más adelante podremos reemplazarlo por un modelo Proveedor.', max_length=200)),
                ('fecha_compra', models.DateField()),
                ('tipo_documento', models.CharField(blank=True, help_text='Factura, boleta, recibo, sin comprobante, etc.', max_length=30)),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('BANCO', 'Banco / transferencia'), ('CREDITO', 'Crédito proveedor'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CONTABILIZADA', 'Contabilizada')], default='PENDIENTE', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('contabilizado_en', models.DateTimeField(blank=True, null=True)),
                ('cuenta_pago', models.ForeignKey(blank=True, help_text='Ej.: 10101 Caja o 10401 Banco. Se usa cuando la compra se paga al contado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_directas_pagadas', to='contabilidad.cuentacontable')),
                ('cuenta_proveedor', models.ForeignKey(blank=True, help_text='Normalmente 42102 Proveedores de lunas cuando la compra queda pendiente de pago.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_directas_credito', to='contabilidad.cuentacontable')),
                ('detalle_costo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compra_directa', to='contabilidad.detallepropuestacostoventa')),
            ],
            options={
                'verbose_name': 'Compra directa para venta',
                'verbose_name_plural': 'Compras directas para venta',
                'ordering': ['-fecha_compra', '-id'],
            },
        ),
    ]
