# Generated by Django 6.0.2 on 2026-08-21 03:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_compradirectaventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioTerceroVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('MEDIDA_VISTA', 'Medida de vista'), ('BISELADO', 'Biselado'), ('COLOREADO', 'Coloreado'), ('FLEX', 'Cambio de Flex'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('proveedor_nombre', models.CharField(blank=True, max_length=200)),
                ('fecha_servicio', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('forma_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('BANCO', 'Banco / transferencia'), ('CREDITO', 'Crédito proveedor'), ('OTRO', 'Otro')], max_length=15)),
                ('estado', models.CharField(choices=[('PROPUESTO', 'Propuesto'), ('CONFIRMADO', 'Confirmado'), ('CONTABILIZADO', 'Contabilizado')], default='PROPUESTO', max_length=20)),
                ('creado_automaticamente', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contabilizado_en', models.DateTimeField(blank=True, null=True)),
                ('cuenta_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_terceros_pagados', to='contabilidad.cuentacontable')),
                ('cuenta_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_terceros_credito', to='contabilidad.cuentacontable')),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_terceros', to='contabilidad.propuestacostoventa')),
            ],
            options={
                'verbose_name': 'Servicio de tercero para venta',
                'verbose_name_plural': 'Servicios de tercero para venta',
                'ordering': ['tipo_servicio', 'id'],
                'constraints': [models.UniqueConstraint(fields=('propuesta', 'tipo_servicio'), name='unique_servicio_tercero_por_propuesta')],
            },
        ),
    ]
