# Generated by Django 6.0.2 on 2026-08-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_servicioterceroventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontable',
            name='clasificacion_balance',
            field=models.CharField(choices=[('ACTIVO_CORRIENTE', 'Activo corriente'), ('ACTIVO_NO_CORRIENTE', 'Activo no corriente'), ('PASIVO_CORRIENTE', 'Pasivo corriente'), ('PASIVO_NO_CORRIENTE', 'Pasivo no corriente'), ('PATRIMONIO', 'Patrimonio'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=30),
        ),
    ]
