# Generated by Django 6.0.2 on 2026-08-29 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_cuentacontable_clasificacion_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='periodocontable',
            name='fecha_reapertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='motivo_reapertura',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='reabierto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_contables_reabiertos', to=settings.AUTH_USER_MODEL),
        ),
    ]
