# Generated by Django 6.0.2 on 2026-08-30 04:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_periodocontable_fecha_reapertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradirectaventa',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha del pago realizado. Puede ser distinta de la fecha de compra.', null=True),
        ),
        migrations.AddField(
            model_name='compradirectaventa',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento de la deuda con el proveedor.', null=True),
        ),
        migrations.AddField(
            model_name='compradirectaventa',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Importe efectivamente pagado al proveedor al momento de registrar la compra.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='compradirectaventa',
            name='cuenta_pago',
            field=models.ForeignKey(blank=True, help_text='Ej.: 10101 Caja o 10401 Banco. Se utiliza cuando existe un pago.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_directas_pagadas', to='contabilidad.cuentacontable'),
        ),
        migrations.AlterField(
            model_name='compradirectaventa',
            name='cuenta_proveedor',
            field=models.ForeignKey(blank=True, help_text='Cuenta por pagar al proveedor. Se utiliza cuando existe saldo pendiente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_directas_credito', to='contabilidad.cuentacontable'),
        ),
        migrations.AlterField(
            model_name='compradirectaventa',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('BANCO', 'Banco / transferencia'), ('CREDITO', 'Crédito proveedor'), ('PARCIAL', 'Pago parcial'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=15),
        ),
    ]
