# Generated by Django 6.0.2 on 2026-08-30 05:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_compradirectaventa_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradirectaventa',
            name='cuenta_pago',
            field=models.ForeignKey(blank=True, help_text='Cuenta utilizada para el pago inicial. Ej.: 10101 Caja o 10401 Banco.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_directas_pagadas', to='contabilidad.cuentacontable'),
        ),
        migrations.AlterField(
            model_name='compradirectaventa',
            name='cuenta_proveedor',
            field=models.ForeignKey(blank=True, help_text='Cuenta por pagar al proveedor cuando existe saldo pendiente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_directas_credito', to='contabilidad.cuentacontable'),
        ),
        migrations.AlterField(
            model_name='compradirectaventa',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha del pago inicial realizado.', null=True),
        ),
        migrations.AlterField(
            model_name='compradirectaventa',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto pagado al proveedor al momento de registrar inicialmente la compra.', max_digits=12),
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('CONTABILIZADO', 'Contabilizado'), ('ANULADO', 'Anulado')], default='REGISTRADO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contabilizado_en', models.DateTimeField(blank=True, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_proveedor', to='contabilidad.compradirectaventa')),
                ('cuenta_pago', models.ForeignKey(help_text='Cuenta desde la que se realizó el pago. Ej.: 10101 Caja o 10401 Banco.', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_a_proveedores', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Pago a proveedor',
                'verbose_name_plural': 'Pagos a proveedores',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
    ]
