# Generated by Django 6.0.2 on 2026-09-02 01:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_alter_compradirectaventa_cuenta_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('descripcion', models.CharField(blank=True, help_text='Detalle adicional de la operación. Ej.: Alquiler correspondiente a agosto 2026.', max_length=300)),
                ('proveedor_nombre', models.CharField(blank=True, max_length=200)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('tipo_documento', models.CharField(blank=True, help_text='Factura, boleta, recibo, voucher, etc.', max_length=50)),
                ('numero_documento', models.CharField(blank=True, max_length=100)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('BANCO', 'Banco / transferencia'), ('CREDITO', 'Crédito'), ('PARCIAL', 'Pago parcial'), ('OTRO', 'Otro')], max_length=20)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONTABILIZADA', 'Contabilizada'), ('ANULADA', 'Anulada')], db_index=True, default='BORRADOR', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contabilizado_en', models.DateTimeField(blank=True, null=True)),
                ('asiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operacion_contable', to='contabilidad.asientocontable')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_contables', to='contabilidad.conceptooperacion')),
                ('cuenta_pago', models.ForeignKey(blank=True, help_text='Cuenta de Caja o Banco utilizada para pagar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_contables_pagadas', to='contabilidad.cuentacontable')),
                ('cuenta_por_pagar', models.ForeignKey(blank=True, help_text='Cuenta por pagar utilizada cuando la operación es al crédito o parcialmente pagada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_contables_por_pagar', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Operación contable',
                'verbose_name_plural': 'Operaciones contables',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
