# Generated by Django 6.0.2 on 2026-09-06 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_operacioncontable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoOperacionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(db_index=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('CONTABILIZADO', 'Contabilizado'), ('ANULADO', 'Anulado')], db_index=True, default='REGISTRADO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contabilizado_en', models.DateTimeField(blank=True, null=True)),
                ('asiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago_operacion_contable', to='contabilidad.asientocontable')),
                ('cuenta_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_operaciones_contables', to='contabilidad.cuentacontable')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_posteriores', to='contabilidad.operacioncontable')),
            ],
            options={
                'verbose_name': 'Pago de operación contable',
                'verbose_name_plural': 'Pagos de operaciones contables',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
    ]
