# Generated by Django 6.0.2 on 2026-09-11 01:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_pagooperacioncontable'),
        ('core', '0012_cliente_excluir_reactivacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('fecha_emision', models.DateField(db_index=True)),
                ('motivo', models.CharField(choices=[('ERROR_PRECIO', 'Error de precio'), ('ANULACION_TOTAL', 'Anulación total de la venta'), ('DEVOLUCION_PRODUCTO', 'Devolución de producto'), ('DESCUENTO_POSTERIOR', 'Descuento posterior'), ('OTRO', 'Otro')], max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_aplicado_saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monto_devuelto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONTABILIZADA', 'Contabilizada'), ('ANULADA', 'Anulada')], db_index=True, default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contabilizado_en', models.DateTimeField(blank=True, null=True)),
                ('asiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nota_credito', to='contabilidad.asientocontable')),
                ('cuenta_devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito_devueltas', to='contabilidad.cuentacontable')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='core.ticketventa')),
            ],
            options={
                'verbose_name': 'Nota de crédito',
                'verbose_name_plural': 'Notas de crédito',
                'ordering': ['-fecha_emision', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devuelve_stock', models.BooleanField(default=False)),
                ('costo_unitario_reversion', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('kardex_generado', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=300)),
                ('detalle_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_notas_credito', to='core.detalleticketventa')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.notacredito')),
            ],
            options={
                'verbose_name': 'Detalle de nota de crédito',
                'verbose_name_plural': 'Detalles de nota de crédito',
                'ordering': ['id'],
            },
        ),
    ]
