# Generated by Django 5.1.4 on 2025-12-31 05:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cajadia_arqueo_efectivo_cajadia_arqueo_tarjeta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('LAB_PEDIDO', 'Pedido al Laboratorio'), ('LAB_EN_PROCESO', 'En Laboratorio'), ('BISELADO', 'En Biselado'), ('UV', 'Desinfección UV'), ('LISTO', 'Lentes Listos'), ('ENTREGADO', 'Entregado')], default='LAB_PEDIDO', max_length=20)),
                ('fecha_hora_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_hora_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ts_lab_pedido', models.DateTimeField(blank=True, null=True)),
                ('ts_biselado', models.DateTimeField(blank=True, null=True)),
                ('ts_uv', models.DateTimeField(blank=True, null=True)),
                ('ts_listo', models.DateTimeField(blank=True, null=True)),
                ('ts_entregado', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden', to='core.ticketventa')),
            ],
        ),
    ]
