# Generated by Django 5.1.4 on 2026-01-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ordentrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipolunas',
            name='colorfotosensible',
            field=models.CharField(blank=True, choices=[('Azul', 'Azul'), ('Verde', 'Verde'), ('Gris', 'Gris'), ('Marron', 'Marrón'), ('Rosado', 'Rosado'), ('Verde', 'Verde grafito'), ('zafiro', 'Zafiro'), ('ambar', 'ámbar'), ('esmeralda', 'Esmeralda'), ('rubi', 'Rubí')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tipolunas',
            name='enfoque',
            field=models.CharField(blank=True, choices=[('Monofocal', 'Monofocal'), ('Bifocal_Fla', 'Bifocal Flat Top:'), ('Bifocal_in', 'Bifocal Invisible:'), ('Multifocal', 'Multifocal'), ('Lentes_Contac', 'Lentes de Contacto')], max_length=20, null=True),
        ),
    ]
