# Generated by Django 5.1.4 on 2026-01-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_perfilusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
