# Generated by Django 6.0.2 on 2026-06-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_conversacionwhatsapp_modo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo', models.CharField(choices=[('ENTRANTE', 'Entrante'), ('SALIENTE', 'Saliente')], max_length=20)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='whatsapp_archivos/')),
                ('wa_message_id', models.CharField(blank=True, max_length=150, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
    ]
