# Generated by Django 6.0.2 on 2026-06-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_mensajewhatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='estado',
            field=models.CharField(choices=[('INICIO', 'Inicio'), ('ESPERANDO_TICKET', 'Esperando Ticket'), ('ESPERANDO_DATOS_CITA', 'Esperando Datos Cita'), ('ESPERANDO_ENCUESTA', 'Esperando Encuesta'), ('ASESOR', 'Asesor'), ('FINALIZADO', 'Finalizado')], default='INICIO', max_length=50),
        ),
    ]
