# Generated by Django 6.0.2 on 2026-06-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_alter_conversacionwhatsapp_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacionwhatsapp',
            name='estado',
            field=models.CharField(choices=[('INICIO', 'Inicio'), ('ESPERANDO_TICKET', 'Esperando Ticket'), ('ESPERANDO_DATOS_CITA', 'Esperando Datos Cita'), ('ESPERANDO_CONFIRMACION_ASESOR', 'Esperando Confirmación Asesor'), ('ASESOR', 'Asesor'), ('FINALIZADO', 'Finalizado')], default='INICIO', max_length=50),
        ),
    ]
