# Generated by Django 6.0.2 on 2026-10-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_alter_conversacionwhatsapp_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('LEIDO', 'Leído'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='wa_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
